select no_plan();
select ok(not has_table_privilege(r,'phi.patients','INSERT'),'No arbitrary patient write for '||r) from unnest(array['anon','authenticated','service_role','gi_api_executor']) r;
select ok(not has_function_privilege('authenticated','private.managed_auth_session()','EXECUTE'),'Managed Auth helper cannot be called by clients');
select ok(not has_function_privilege('service_role','private.request_uid()','EXECUTE'),'Service API cannot call private identity helper');
select ok(not has_column_privilege('gi_policy_reader','auth.sessions','id','SELECT'),'Policy role has no direct managed-session read');
select ok(c.relrowsecurity and c.relforcerowsecurity, format('%I.%I requires enabled and forced RLS',n.nspname,c.relname)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('app','phi','audit') and c.relkind in('r','p');
select ok(not has_schema_privilege(r,'api','CREATE') and not has_schema_privilege(r,'private','CREATE'),'Executor cannot create or replace functions: '||r) from unnest(array['gi_api_executor','gi_policy_reader','gi_metadata_reader','gi_audit_writer']) r;
select ok(not has_table_privilege(r,'audit.audit_events',p),r||' cannot '||p||' audit events') from unnest(array['anon','authenticated','service_role','gi_api_executor','gi_audit_writer']) r cross join unnest(array['UPDATE','DELETE','TRUNCATE']) p;
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='phi.patients'::regclass),'Patient RLS enabled and forced');
select ok(not has_table_privilege('authenticated','phi.patients','SELECT'),'Authenticated cannot read table directly');
select ok(not has_table_privilege('service_role','phi.patients','SELECT'),'Service API has no patient table grant');
select ok(has_table_privilege('gi_api_executor','audit.audit_events','SELECT'),'Executor can perform audited admin reads');
select ok(not has_table_privilege('authenticated','audit.audit_events','SELECT'),'Admin user role has no direct audit table read');
select ok(not has_table_privilege('service_role','audit.audit_events','TRUNCATE'),'Service role cannot truncate audit');
select ok(not has_table_privilege('gi_audit_writer','audit.audit_events','DELETE'),'Writer cannot delete audit');
select ok(not has_table_privilege('gi_api_executor','audit.audit_events','UPDATE'),'Executor cannot mutate audit');
select ok(not has_function_privilege('authenticated','private.record_access(text,uuid,text,text,text,uuid[],text,uuid)','EXECUTE'),'Private audit writer cannot be called by client');
select ok(has_function_privilege('anon','api.environment()','EXECUTE'),'Bootstrap works before login');
select ok(not has_function_privilege('anon','api.list_patients(uuid,text,integer,integer)','EXECUTE'),'Anonymous cannot enter patient reader');
select ok((select not rolcanlogin and not rolbypassrls from pg_roles where rolname='gi_api_executor'),'Executor cannot log in or bypass RLS');
select ok((select proowner<>relowner from pg_proc,pg_class where pg_proc.oid='api.list_patients(uuid,text,integer,integer)'::regprocedure and pg_class.oid='phi.patients'::regclass),'Reader does not own protected table');
select ok((select provolatile='v' from pg_proc where oid='api.list_audit_events(uuid,timestamptz,timestamptz,text,integer,integer)'::regprocedure),'Audited reads permit writes');
select * from finish();
