-- Legacy encounter regression; transaction rollback restores the current default.
alter table phi.encounters alter column content_version set default 'demo-draft-2026-09-21';
select no_plan();
insert into auth.users(id,email,role,aud) values('91000000-0000-4000-8000-000000000001','demo-sql@demo.invalid','authenticated','authenticated');
insert into auth.sessions(id,user_id,created_at,updated_at) values('91000000-0000-4000-8000-000000000002','91000000-0000-4000-8000-000000000001',now(),now());
insert into app.staff_accounts(user_id,synthetic_key) values('91000000-0000-4000-8000-000000000001','SYN-DEMO-SQL');
insert into app.sites(id,name) values('91000000-0000-4000-8000-000000000003','SYN Demo SQL'),('91000000-0000-4000-8000-000000000004','SYN Foreign SQL');
insert into app.site_memberships values('91000000-0000-4000-8000-000000000001','91000000-0000-4000-8000-000000000003','clinician',true);
insert into phi.patients(id,site_id,synthetic_identifier,display_name,year_of_birth,is_synthetic) values('91000000-0000-4000-8000-000000000005','91000000-0000-4000-8000-000000000003','SYN-DEMO-SQL-P','Fictional SQL patient',1970,true),('91000000-0000-4000-8000-000000000006','91000000-0000-4000-8000-000000000004','SYN-DEMO-SQL-FOREIGN','Fictional foreign patient',1970,true);
select set_config('test.claims','{"sub":"91000000-0000-4000-8000-000000000001","session_id":"91000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select is(api.begin_staff_session()->>'ok','true','demo staff session begins');
select throws_ok('select * from phi.encounters','42501',null,'browser cannot read encounter tables');
select is(api.demo_action('create','91000000-0000-4000-8000-000000000006')->>'ok','false','cannot create for a foreign-site patient');
select set_config('test.encounter',api.demo_action('create','91000000-0000-4000-8000-000000000005')->'data'->>'id',true);
select ok(current_setting('test.encounter') is not null,'staff creates an encounter');
select is(api.demo_action('get',current_setting('test.encounter')::uuid)->'data'->>'status','awaiting_consent','new encounter awaits consent');
select set_config('test.cap',api.demo_action('handoff',current_setting('test.encounter')::uuid)->'data'->>'token',true);
select is(length(current_setting('test.cap')),64,'handoff has 256 bits of entropy');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(api.demo_action('get',current_setting('test.encounter')::uuid,repeat('a',64))->>'ok','false','wrong capability denied');
select is(api.demo_action('get',gen_random_uuid(),current_setting('test.cap'))->>'ok','false','capability cannot read another encounter');
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"version":0,"intake":{}}')->>'ok','false','clinical save denied before consent');
select is(api.demo_action('consent',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"accepted":true,"noticeVersion":"synthetic-demo-notice-v1"}')->>'ok','true','versioned consent recorded');
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"version":0,"intake":{"name":"Fictional patient","age":52,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":6,"answers":{"vomit_blood":"Yes","conditions":"Not sure"}}}')->>'ok','true','consented answers persist');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answers'->>'conditions','Not sure','unknown remains unknown');
reset role;
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select is(api.demo_action('review_partial',current_setting('test.encounter')::uuid)->>'ok','true','clinician can take saved incomplete intake for review');
select is(api.demo_action('message',current_setting('test.encounter')::uuid,null,'{"text":"Please confirm when the symptoms began."}')->>'ok','true','clinician can request clarification');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'messages'->0->>'author','clinician','patient sees clinician clarification with authorship');
select is(api.demo_action('message',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"text":"Symptoms began several days ago."}')->>'ok','true','patient can reply within encounter');
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"version":1,"intake":{}}')->>'ok','false','stale intake tab cannot overwrite active clinician review');
select is(api.demo_action('reopen',current_setting('test.encounter')::uuid,current_setting('test.cap'))->>'ok','true','explicit correction reopens intake');
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"version":0,"intake":{}}')->>'error','version_conflict','stale save refused');
select is(api.demo_action('release',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"review":{}}')->>'ok','false','patient cannot release assessment');
select is(api.demo_action('report_get',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"reportId":"91000000-0000-4000-8000-000000000099"}')->>'ok','false','missing report denied');
select is(api.demo_action('submit',current_setting('test.encounter')::uuid,current_setting('test.cap'))->>'ok','true','submission queues durable analysis');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'job'->>'status','queued','job persists independently of browser');
reset role;
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select is(api.demo_action('reveal',current_setting('test.encounter')::uuid)->>'ok','false','AI reveal blocked before independent assessment');
select is(api.demo_action('draft',current_setting('test.encounter')::uuid,null,'{"sourceVersion":1,"review":{"impression":"Stale draft"}}')->>'ok','false','stale source draft is rejected');
select is(api.demo_action('independent',current_setting('test.encounter')::uuid,null,'{"sourceVersion":1,"review":{"impression":"Stale assessment"}}')->>'ok','false','independent assessment cannot sign a newer intake');
select is(api.demo_action('draft',current_setting('test.encounter')::uuid,null,'{"sourceVersion":2,"review":{"impression":"Draft","plan":"Draft","privateNotes":"Private note sentinel"}}')->>'ok','true','draft saves without unblinding');
select is(api.demo_action('get',current_setting('test.encounter')::uuid)->'data'->'independentAt','null'::jsonb,'draft does not freeze independent assessment');
select throws_ok($$select api.demo_action('independent',current_setting('test.encounter')::uuid,null,'{"sourceVersion":2,"review":{"impression":"Possible bleeding","specialty":"Gastroenterology","urgency":"review","plan":"Seek assessment","privateNotes":"Private note sentinel"}}')$$,'P0001','Urgency below minimum','direct RPC cannot lower urgency');
select is(api.demo_action('independent',current_setting('test.encounter')::uuid,null,'{"sourceVersion":2,"review":{"impression":"Possible upper GI bleeding","specialty":"Emergency department","urgency":"immediate","plan":"Seek immediate hospital assessment","privateNotes":"Private note sentinel","priorExposure":"not_exposed","disagreement":"not_compared","reason":""}}')->>'ok','true','independent assessment saves');
select is(api.demo_action('reveal',current_setting('test.encounter')::uuid)->>'ok','true','saved assessment unlocks AI');
select is(api.demo_action('release',current_setting('test.encounter')::uuid,null,'{"sourceVersion":1,"review":{"impression":"Stale plan"}}')->>'ok','false','released plan must reference current reviewed source');
select is(api.demo_action('release',current_setting('test.encounter')::uuid,null,'{"sourceVersion":2,"review":{"impression":"Possible upper GI bleeding","specialty":"Emergency department","urgency":"immediate","plan":"Seek immediate hospital assessment","privateNotes":"Private note sentinel","priorExposure":"not_exposed","disagreement":"not_compared","reason":"Internal correction sentinel"}}')->>'ok','true','clinician alone releases plan');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select ok(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))::text not like '%Private note sentinel%','patient projection excludes all private notes including drafts');
select ok(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))::text not like '%Internal correction sentinel%','patient projection excludes internal feedback');
select is(api.demo_action('message',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"text":"Late reply"}')->>'ok','false','released encounter messages are read-only');
select is(api.demo_action('reset',current_setting('test.encounter')::uuid,current_setting('test.cap'))->>'ok','true','patient can revoke capability');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->>'ok','false','reset capability is unusable');
reset role;
select ok(exists(select 1 from audit.audit_events where action='demo_get' and outcome='denied_or_not_found' and purpose='patient_encounter'),'denials are audit logged');
select ok(exists(select 1 from audit.audit_events where action='demo_release' and record_ids=array[current_setting('test.encounter')::uuid] and outcome='allowed'),'release audit records encounter');
select throws_ok('truncate phi.encounter_versions','P0001','Audit history is append-only','source revisions are append-only');
select * from finish();
