-- Legacy encounter regression; transaction rollback restores the current default.
alter table phi.encounters alter column content_version set default 'demo-draft-2026-09-21';
select no_plan();
insert into auth.users(id,email,role,aud) values('92000000-0000-4000-8000-000000000001','workflow@demo.invalid','authenticated','authenticated');
insert into auth.sessions(id,user_id,created_at,updated_at) values('92000000-0000-4000-8000-000000000002','92000000-0000-4000-8000-000000000001',now(),now());
insert into app.staff_accounts(user_id,synthetic_key) values('92000000-0000-4000-8000-000000000001','SYN-WORKFLOW-SQL');
insert into app.sites(id,name) values('92000000-0000-4000-8000-000000000003','SYN workflow clinic');
insert into app.site_memberships values('92000000-0000-4000-8000-000000000001','92000000-0000-4000-8000-000000000003','clinician',true);
insert into app.intake_sites(site_id,slug,enabled) values('92000000-0000-4000-8000-000000000003','workflow-test',true);
select set_config('request.jwt.claims','{}',true);
set local role anon;
select throws_ok($$select api.patient_start('workflow-test')$$,'42501',null,'anonymous browser cannot bypass server entry boundary');
select throws_ok($$select api.report_worker('claim')$$,'42501',null,'anonymous browser cannot run extraction jobs');
reset role;set local role service_role;
select set_config('test.entry',api.patient_start('workflow-test')::text,true);
select is(current_setting('test.entry')::jsonb->>'ok','true','server starts anonymous assigned encounter');
select set_config('test.eid',current_setting('test.entry')::jsonb->'data'->>'id',true);
select set_config('test.cap',current_setting('test.entry')::jsonb->'data'->>'token',true);
reset role;
select ok((select assigned_to is not null and intake='{}'::jsonb and consent_at is null from phi.encounters where id=current_setting('test.eid')::uuid),'entry stores no clinical answers before consent');
set local role anon;
select is(api.demo_action('consent',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"accepted":true,"noticeVersion":"gi-privacy-2026-09-22"}')->>'ok','true','new privacy notice consent is recorded');
select is(api.demo_action('report_add',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"name":"synthetic.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[{"id":"forged","verified":true}],"quality":"pending"}')->>'ok','true','optional report accepted for processing');
reset role;
select set_config('test.report',(select id::text from phi.demo_reports where encounter_id=current_setting('test.eid')::uuid),true);
select is((select fields from phi.demo_reports where id=current_setting('test.report')::uuid),'[]'::jsonb,'upload cannot forge verified model evidence');
set local role anon;
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,current_setting('test.cap'),jsonb_build_object('reportId',current_setting('test.report'),'fields','[]'::jsonb,'sourceVersion',1))->>'ok','false','patient cannot verify report evidence');
select is(api.demo_action('get',current_setting('test.eid')::uuid,repeat('0',64))->>'ok','false','different capability cannot read anonymous visit');
reset role;set local role service_role;
select set_config('test.job',api.report_worker('claim')::text,true);
select is(current_setting('test.job')::jsonb->>'ok','true','worker leases saved report');
select is(api.report_worker('complete',(current_setting('test.job')::jsonb->'data'->>'id')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,'{"fields":[{"id":"p1-f1","label":"Haemoglobin","value":"10.4","unit":"g/dL","page":1,"sourceText":"Haemoglobin 10.4 g/dL","date":"","confidence":"text-extracted","verified":true}],"quality":"Ready for verification"}')->>'ok','true','worker publishes extracted proposals');
reset role;
select is((select fields->0->>'verified' from phi.demo_reports where id=current_setting('test.report')::uuid),'false','worker output is unverified even if model proposes true');
select set_config('request.jwt.claims','{"sub":"92000000-0000-4000-8000-000000000001","session_id":"92000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
set local role authenticated;
select is(api.begin_staff_session()->>'ok','true','staff session begins');
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report'),'sourceVersion',0,'fields','[]'::jsonb))->>'ok','false','stale verification cannot overwrite newer evidence');
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report'),'sourceVersion',1,'fields','[{"id":"p1-f1","label":"Haemoglobin","value":"10.4","unit":"g/dL","page":1,"sourceText":"Haemoglobin 10.4 g/dL","date":"","confidence":"text-extracted","verified":true}]'::jsonb))->>'ok','true','staff can verify report against current source version');
reset role;
select is((select count(*)::int from phi.report_revisions where report_id=current_setting('test.report')::uuid),2,'extraction and verification retain append-only previous fields');
select is((select version from phi.encounters where id=current_setting('test.eid')::uuid),2,'verified evidence advances encounter source version');
select ok(exists(select 1 from audit.audit_events where action='demo_report_verify' and record_ids=array[current_setting('test.eid')::uuid] and outcome='allowed'),'staff verification has an audit entry');
set local role authenticated;
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report'),'sourceVersion',2,'fields','[]'::jsonb))->>'ok','true','staff can withdraw all accepted findings');
reset role;
select ok((select verified_at is null from phi.demo_reports where id=current_setting('test.report')::uuid),'empty evidence is not shown as staff verified');
update phi.demo_reports set extraction_status='running',extraction_until=now()-interval '1 minute',extraction_attempts=3 where id=current_setting('test.report')::uuid;
set local role service_role;
select is(api.report_worker('claim',gen_random_uuid())->'data','null'::jsonb,'targeted report claim cannot lease a different report');
reset role;
select is((select extraction_status from phi.demo_reports where id=current_setting('test.report')::uuid),'failed','exhausted expired extraction becomes terminal instead of hanging');
update phi.demo_reports set extraction_status='queued',extraction_attempts=0 where id=current_setting('test.report')::uuid;
set local role service_role;
select set_config('test.job',api.report_worker('claim',current_setting('test.report')::uuid)::text,true);
reset role;
update phi.encounters set consent_at=null where id=current_setting('test.eid')::uuid;
set local role service_role;
select is(api.report_worker('complete',current_setting('test.report')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,'{"fields":[],"quality":"Complete"}')->>'ok','false','withdrawn consent prevents report publication');
reset role;
update app.intake_limits set starts=120 where site_id='92000000-0000-4000-8000-000000000003';
set local role service_role;
select is(api.patient_start('workflow-test')->>'error','try_later','database rate limit stops repeated public starts');
select * from finish();
