select no_plan();
-- Entirely fictional, inside the runner's rolled-back transaction.
insert into auth.users(id,email,role,aud) values('92000000-0000-4000-8000-000000000001','contextual-sql@demo.invalid','authenticated','authenticated');
insert into auth.sessions(id,user_id,created_at,updated_at) values('92000000-0000-4000-8000-000000000002','92000000-0000-4000-8000-000000000001',now(),now());
insert into app.staff_accounts(user_id,synthetic_key) values('92000000-0000-4000-8000-000000000001','SYN-CONTEXT-SQL');
insert into app.sites(id,name) values('92000000-0000-4000-8000-000000000003','SYN Context SQL');
insert into app.site_memberships values('92000000-0000-4000-8000-000000000001','92000000-0000-4000-8000-000000000003','clinician',true);
insert into phi.patients(id,site_id,synthetic_identifier,display_name,year_of_birth,is_synthetic) values('92000000-0000-4000-8000-000000000005','92000000-0000-4000-8000-000000000003','SYN-CONTEXT-SQL-P','Fictional contextual patient',1986,true);
select set_config('test.claims','{"sub":"92000000-0000-4000-8000-000000000001","session_id":"92000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select is(api.begin_staff_session()->>'ok','true','contextual staff session begins');
select set_config('test.encounter',api.demo_action('create','92000000-0000-4000-8000-000000000005')->'data'->>'id',true);
select is(api.demo_action('get',current_setting('test.encounter')::uuid)->'data'->>'contentVersion','intake-draft-2026-09-22.2','created encounter is pinned to current content');
select is(api.demo_action('queue','92000000-0000-4000-8000-000000000003')->'data'->0->>'contentVersion','intake-draft-2026-09-22.2','queue carries the content version');
select set_config('test.cap',api.demo_action('handoff',current_setting('test.encounter')::uuid)->'data'->>'token',true);
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(api.demo_action('get',gen_random_uuid(),current_setting('test.cap'))->>'ok','false','new content does not weaken cross-patient denial');
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"version":0,"intake":{}}')->>'ok','false','new questionnaire still requires consent');
select is(api.demo_action('consent',current_setting('test.encounter')::uuid,current_setting('test.cap'),'{"accepted":true,"noticeVersion":"synthetic-demo-notice-v1"}')->>'ok','true','current questionnaire consent recorded');
select set_config('test.intake','{"name":"Fictional contextual patient","age":40,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":2,"answers":{"pain_presence":"Pain is present now","pain_now_severity":"Unbearable pain","pain_site":"[\"Right upper\",\"Upper middle\"]","pain_site__note":"Fictional additional detail"},"answerSources":{"pain_presence":{"suppliedBy":"patient","enteredBy":"patient"},"pain_now_severity":{"suppliedBy":"caregiver","enteredBy":"coordinator"}}}',true);
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),jsonb_build_object('version',0,'intake',current_setting('test.intake')::jsonb))->>'ok','true','current multi-location answers and detail save through capability RPC');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answers'->>'pain_site__note','Fictional additional detail','free detail round trips');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answerSources'->'pain_now_severity'->>'suppliedBy','caregiver','per-answer supplier round trips');
select throws_ok($$select api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),jsonb_build_object('version',1,'intake',jsonb_set(current_setting('test.intake')::jsonb,'{answers,pain_site}','"[\"Right upper\",\"Not sure\"]"'::jsonb)))$$,'P0001','Invalid answer','direct RPC refuses ambiguous multi-selection');
select set_config('test.intake',((api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake')-'answerSources')::text,true);
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),jsonb_build_object('version',1,'intake',current_setting('test.intake')::jsonb||'{"suppliedBy":"caregiver","enteredBy":"coordinator"}'::jsonb))->>'ok','true','stale client may omit source map when assistance changes');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answerSources'->'pain_presence'->>'suppliedBy','patient','server preserves original patient supplier after assistance changes');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answerSources'->'pain_site__note'->>'enteredBy','patient','server preserves source of unchanged notes too');
select set_config('test.intake',((api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake')-'answerSources')::text,true);
select is(api.demo_action('save',current_setting('test.encounter')::uuid,current_setting('test.cap'),jsonb_build_object('version',2,'intake',jsonb_set(current_setting('test.intake')::jsonb,'{answers,pain_onset}','"Gradually, over hours or days"'::jsonb)))->>'ok','true','new answer saves without client source map');
select is(api.demo_action('get',current_setting('test.encounter')::uuid,current_setting('test.cap'))->'data'->'intake'->'answerSources'->'pain_onset'->>'suppliedBy','caregiver','server records the declared supplier for new answers');
select is(api.demo_action('submit',current_setting('test.encounter')::uuid,current_setting('test.cap'))->>'ok','true','contextual intake can submit with immediate floor and unanswered questions');
reset role;
select is((select snapshot->>'contentVersion' from phi.demo_jobs where encounter_id=current_setting('test.encounter')::uuid),'intake-draft-2026-09-22.2','durable AI snapshot pins revised content');
select throws_ok($$update phi.encounters set content_version='demo-draft-2026-09-21' where id=current_setting('test.encounter')::uuid$$,'P0001','Content version is immutable','historical rules cannot be silently rewritten');
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select throws_ok($$select api.demo_action('independent',current_setting('test.encounter')::uuid,null,'{"sourceVersion":3,"review":{"impression":"Fictional assessment","specialty":"Gastroenterology","urgency":"review","plan":"Clinical review","privateNotes":""}}')$$,'P0001','Urgency below minimum','current linked floor also protects direct clinician RPC');
reset role;
select ok(exists(select 1 from audit.audit_events where action='demo_save' and outcome='allowed' and record_ids @> array[current_setting('test.encounter')::uuid] and purpose='patient_encounter'),'new-format answers retain atomic capability audit');
select * from finish();
