select no_plan();
-- Fictional rows, rolled back by the isolated test runner.
insert into auth.users(id,email,role,aud) values('93000000-0000-4000-8000-000000000001','recovery@demo.invalid','authenticated','authenticated');
insert into auth.sessions(id,user_id,created_at,updated_at) values('93000000-0000-4000-8000-000000000002','93000000-0000-4000-8000-000000000001',now(),now());
insert into app.staff_accounts(user_id,synthetic_key) values('93000000-0000-4000-8000-000000000001','SYN-RECOVERY-SQL');
insert into app.sites(id,name) values('93000000-0000-4000-8000-000000000003','SYN recovery clinic');
insert into app.site_memberships values('93000000-0000-4000-8000-000000000001','93000000-0000-4000-8000-000000000003','clinician',true);
insert into app.intake_sites(site_id,slug,enabled) values('93000000-0000-4000-8000-000000000003','recovery-test',true);
select set_config('request.jwt.claims','{}',true);
set local role service_role;
select set_config('test.entry',api.patient_start('recovery-test')::text,true);
select set_config('test.eid',current_setting('test.entry')::jsonb->'data'->>'id',true);
select set_config('test.cap',current_setting('test.entry')::jsonb->'data'->>'token',true);
reset role;set local role anon;
select is(api.demo_action('consent',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"accepted":true,"noticeVersion":"gi-privacy-2026-09-22"}')->>'ok','true','report recovery visit consent');
select is(api.demo_action('report_add',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"name":"fictional.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[],"quality":"pending"}')->>'ok','true','report uploaded into durable queue');
select set_config('test.report',api.demo_action('get',current_setting('test.eid')::uuid,current_setting('test.cap'))->'data'->'reports'->0->>'id',true);
reset role;set local role service_role;
select set_config('test.job',api.report_worker('claim',current_setting('test.report')::uuid)::text,true);
select is(api.report_worker('heartbeat',current_setting('test.report')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,'{"pagesDone":1,"totalPages":3,"sourceText":"must not be stored"}')->>'ok','true','worker renews lease and reports progress');
reset role;
select is((select extraction_metadata from phi.demo_reports where id=current_setting('test.report')::uuid),'{"pagesDone":1,"totalPages":3}'::jsonb,'only bounded page counts stored from progress');
set local role service_role;
select is(api.report_worker('fail',current_setting('test.report')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,null,'provider_rate_limited')->>'ok','true','worker records known failure');
reset role;set local role anon;
select is(api.demo_action('get',current_setting('test.eid')::uuid,current_setting('test.cap'))->'data'->'reports'->0->>'extractionError','provider_rate_limited','safe failure reason reaches report UI');
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,current_setting('test.cap'),jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','patient cannot trigger external report reprocessing');
reset role;
select set_config('test.claims','{"sub":"93000000-0000-4000-8000-000000000001","session_id":"93000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select is(api.begin_staff_session()->>'ok','true','recovery staff session');
reset role;
update phi.encounters set clinician_draft='{"impression":"GERD","plan":"Review","specialty":"Gastroenterology","urgency":"review"}' where id=current_setting('test.eid')::uuid;
set local role authenticated;
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report'),'sourceVersion',1,'fields','[]'::jsonb))->>'ok','true','unchanged empty verification is an audited no-op');
select is(api.demo_action('get',current_setting('test.eid')::uuid)->'data'->'draft'->>'impression','GERD','empty report verification preserves the clinician draft');
reset role;
select is((select version from phi.encounters where id=current_setting('test.eid')::uuid),1,'unchanged verification preserves source version');
select is((select count(*)::int from phi.demo_jobs where encounter_id=current_setting('test.eid')::uuid),0,'unchanged verification does not enqueue an assessment');
set local role authenticated;
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',gen_random_uuid()))->>'ok','false','cannot retry a report outside this encounter');
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','true','staff can retry failed empty evidence');
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','duplicate retry cannot requeue an active job');
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report'),'sourceVersion',1,'fields','[]'::jsonb))->>'ok','false','even empty verification cannot mutate a queued report');
reset role;
select ok((select extraction_attempts=0 and extraction_error is null and extraction_metadata is null and extraction_lease is null from phi.demo_reports where id=current_setting('test.report')::uuid),'retry clears only processing state');
select is((select version from phi.encounters where id=current_setting('test.eid')::uuid),1,'retry preserves clinician source version');
select ok(exists(select 1 from audit.audit_events where action='demo_report_retry' and outcome='allowed' and record_ids=array[current_setting('test.eid')::uuid]),'retry is audited');
set local role service_role;
select is(api.report_worker('complete',current_setting('test.report')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,'{"fields":[],"quality":"Complete"}')->>'ok','false','old worker cannot publish after retry');
select set_config('test.job',api.report_worker('claim',current_setting('test.report')::uuid)::text,true);
reset role;
update phi.demo_reports set extraction_until=now()-interval '1 minute' where id=current_setting('test.report')::uuid;
set local role authenticated;
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','true','staff can recover abandoned running job');
reset role;set local role service_role;
select set_config('test.job',api.report_worker('claim',current_setting('test.report')::uuid)::text,true);
select is(api.report_worker('fail',current_setting('test.report')::uuid,(current_setting('test.job')::jsonb->'data'->>'lease')::uuid,null,'untrusted content')->>'ok','true','unknown provider error safely recorded');
reset role;
select is((select extraction_error from phi.demo_reports where id=current_setting('test.report')::uuid),'extraction_unavailable','raw provider text is never exposed');
update phi.demo_reports set verified_at=now() where id=current_setting('test.report')::uuid;
set local role authenticated;
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','staff verified report cannot be re-extracted');
reset role;
update phi.demo_reports set verified_at=null,fields='[{"id":"manual","label":"Fictional finding","value":"1","sourceText":"1","verified":false}]' where id=current_setting('test.report')::uuid;
set local role authenticated;
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','retry cannot overwrite saved manual evidence');
reset role;
update phi.demo_reports set fields='[]' where id=current_setting('test.report')::uuid;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(api.demo_action('save',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"version":1,"intake":{"name":"Fictional patient","age":40,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":2,"answers":{},"navigation":{"flowVersion":"intake-flow-draft-2026-09-22.1","topicId":"pain","mode":"main"}}}')->>'ok','true','saved topic round-trips alongside incomplete answers');
select is(api.demo_action('submit',current_setting('test.eid')::uuid,current_setting('test.cap'))->>'ok','true','partial answers remain clinician-assigned');
reset role;
select set_config('request.jwt.claims',current_setting('test.claims'),true);
set local role authenticated;
select throws_ok($$select api.demo_action('independent',current_setting('test.eid')::uuid,null,'{"sourceVersion":2,"review":{"impression":" \t\n","specialty":"Gastroenterology","urgency":"review","plan":"Review"}}')$$,'P0001','Incomplete independent assessment','whitespace-only impression is rejected');
select is(api.demo_action('independent',current_setting('test.eid')::uuid,null,'{"sourceVersion":1,"review":{"impression":"IBS","specialty":"Gastroenterology","urgency":"review","plan":"Review"}}')->>'ok','false','short impression cannot bypass source-version guard');
select is(api.demo_action('independent',current_setting('test.eid')::uuid,null,'{"sourceVersion":2,"review":{"impression":"IBS","specialty":"Gastroenterology","urgency":"review","plan":"Review"}}')->>'ok','true','short independent impression saves');
select is(api.demo_action('get',current_setting('test.eid')::uuid)->'data'->'independent'->>'impression','IBS','short clinical text preserved');
reset role;
update phi.encounters set consent_at=null where id=current_setting('test.eid')::uuid;
set local role authenticated;
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','withdrawn consent prevents retry');
reset role;
update phi.encounters set consent_at=now() where id=current_setting('test.eid')::uuid;
set local role authenticated;
select throws_ok($$select api.demo_action('release',current_setting('test.eid')::uuid,null,'{"sourceVersion":2,"review":{"impression":"IBS","specialty":"Gastroenterology","urgency":"review","plan":" \t\n"}}')$$,'P0001','Incomplete release','whitespace-only released instructions are rejected');
select is(api.demo_action('release',current_setting('test.eid')::uuid,null,'{"sourceVersion":2,"review":{"impression":"IBS","specialty":"Gastroenterology","urgency":"review","plan":"See GP"}}')->>'ok','true','short clinical impression remains valid on release');
select is(api.demo_action('report_retry',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.report')))->>'ok','false','released encounter cannot retry report extraction');
reset role;
select * from finish();
