select no_plan();
-- Entirely fictional, isolated and rolled back by the SQL test runner.
insert into auth.users(id,email,role,aud) values('94000000-0000-4000-8000-000000000001','automatic@demo.invalid','authenticated','authenticated');
insert into auth.sessions(id,user_id,created_at,updated_at) values('94000000-0000-4000-8000-000000000002','94000000-0000-4000-8000-000000000001',now(),now());
insert into app.staff_accounts(user_id,synthetic_key) values('94000000-0000-4000-8000-000000000001','SYN-AUTOMATIC-SQL');
insert into app.sites(id,name) values('94000000-0000-4000-8000-000000000003','SYN automatic reports');
insert into app.site_memberships values('94000000-0000-4000-8000-000000000001','94000000-0000-4000-8000-000000000003','clinician',true);
insert into app.intake_sites(site_id,slug,enabled) values('94000000-0000-4000-8000-000000000003','automatic-test',true);
select set_config('request.jwt.claims','{}',true);
set local role service_role;
select set_config('test.entry',api.patient_start('automatic-test')::text,true);
select set_config('test.eid',current_setting('test.entry')::jsonb->'data'->>'id',true);
select set_config('test.cap',current_setting('test.entry')::jsonb->'data'->>'token',true);
reset role;set local role anon;
select is(api.demo_action('consent',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"accepted":true,"noticeVersion":"gi-privacy-2026-09-26"}')->>'ok','true','automatic evidence accepts the versioned new notice');
select is(api.demo_action('save',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"version":0,"intake":{"name":"Fictional automatic patient","age":40,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":5,"answers":{}}}')->>'ok','true','fictional intake saved');
select is(api.demo_action('report_add',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"name":"fictional-ultrasound.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[],"quality":"pending"}')->>'ok','true','first automatic report accepted');
select is(api.demo_action('report_add',current_setting('test.eid')::uuid,current_setting('test.cap'),'{"name":"fictional-ct.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[],"quality":"pending"}')->>'ok','true','second automatic report accepted');
select is(api.demo_action('submit',current_setting('test.eid')::uuid,current_setting('test.cap'))->>'ok','true','submit while reports are pending is allowed');
reset role;
select set_config('test.r1',(select id::text from phi.demo_reports where encounter_id=current_setting('test.eid')::uuid and name='fictional-ultrasound.pdf'),true);
select set_config('test.r2',(select id::text from phi.demo_reports where encounter_id=current_setting('test.eid')::uuid and name='fictional-ct.pdf'),true);
select set_config('test.version',(select version::text from phi.encounters where id=current_setting('test.eid')::uuid),true);
select set_config('test.initialjob',(select id::text from phi.demo_jobs where encounter_id=current_setting('test.eid')::uuid and source_version=current_setting('test.version')::int),true);
update phi.encounters set clinician_draft='{"impression":"Saved fictional draft","plan":"Review","specialty":"Gastroenterology","urgency":"review"}',draft_source_version=version where id=current_setting('test.eid')::uuid;
set local role service_role;
select is(api.demo_worker('claim',current_setting('test.initialjob')::uuid)->'data','null'::jsonb,'assessment waits for pending reports');
select set_config('test.lease',api.report_worker('claim',current_setting('test.r1')::uuid)->'data'->>'lease',true);
select set_config('test.validfield','{"id":"p1-f1","label":"Printed observation","value":"Fictional observation","unit":"","page":1,"sourceText":"Fictional observation","date":"2026-09-01","reportType":"ultrasound","confidence":"text-extracted","verified":false}',true);
select is(api.report_worker('complete',current_setting('test.r1')::uuid,current_setting('test.lease')::uuid,
 jsonb_build_object('fields',jsonb_build_array(current_setting('test.validfield')::jsonb||bad.patch),'quality','Available'))->>'ok','false','worker rejects malformed automatic field: '||bad.label)
 from (values ('page zero','{"page":0}'::jsonb),('fractional page','{"page":1.5}'),('missing label','{"label":null}'),('oversized label',jsonb_build_object('label',repeat('x',121))),('unsupported type','{"reportType":"invented"}'),('string verification','{"verified":"false"}'),('nonstring source','{"sourceText":5}')) bad(label,patch);
select is(api.report_worker('complete',current_setting('test.r1')::uuid,current_setting('test.lease')::uuid,jsonb_build_object('fields',jsonb_build_array(current_setting('test.validfield')::jsonb)))->>'ok','false','worker rejects missing extraction quality');
select is(api.report_worker('complete',current_setting('test.r1')::uuid,current_setting('test.lease')::uuid,jsonb_build_object('fields',jsonb_build_array(current_setting('test.validfield')::jsonb),'quality',''))->>'ok','false','worker rejects empty extraction quality');
select is(api.report_worker('complete',current_setting('test.r1')::uuid,current_setting('test.lease')::uuid,'{"fields":[{"id":"p1-f1","label":"Printed observation","value":"Fictional observation","unit":"","page":1,"sourceText":"Fictional observation","date":"2026-09-01","reportType":"ultrasound","confidence":"text-extracted","verified":true}],"quality":"Available","provider":"gemini","promptVersion":"test"}')->>'ok','true','machine extraction publishes without staff action');
reset role;
select is((select version from phi.encounters where id=current_setting('test.eid')::uuid),current_setting('test.version')::int+1,'completed report advances submitted source version');
select is((select status from phi.demo_jobs where id=current_setting('test.initialjob')::uuid),'cancelled','older pending assessment is cancelled');
select is((select clinician_draft->>'impression' from phi.encounters where id=current_setting('test.eid')::uuid),'Saved fictional draft','automatic evidence never erases authored draft');
select is((select draft_source_version from phi.encounters where id=current_setting('test.eid')::uuid),current_setting('test.version')::int,'retained draft stays linked to the old facts');
select set_config('test.nextjob',(select id::text from phi.demo_jobs where encounter_id=current_setting('test.eid')::uuid and status='queued'),true);
select is((select r->>'name' from phi.demo_jobs j cross join lateral jsonb_array_elements(j.snapshot->'reports') r where j.id=current_setting('test.nextjob')::uuid and r->>'id'=current_setting('test.r1')),'fictional-ultrasound.pdf','job snapshot retains document name');
select is((select r->'fields'->0->>'verified' from phi.demo_jobs j cross join lateral jsonb_array_elements(j.snapshot->'reports') r where j.id=current_setting('test.nextjob')::uuid and r->>'id'=current_setting('test.r1')),'false','automatic evidence is never falsely staff verified');
set local role service_role;
select is(api.demo_worker('claim',current_setting('test.nextjob')::uuid)->'data','null'::jsonb,'second pending report also blocks an incomplete snapshot');
select set_config('test.lease',api.report_worker('claim',current_setting('test.r2')::uuid)->'data'->>'lease',true);
select is(api.report_worker('fail',current_setting('test.r2')::uuid,current_setting('test.lease')::uuid,null,'invalid_output')->>'ok','true','report failure is terminal and explicit');
reset role;
select set_config('test.currentjob',(select id::text from phi.demo_jobs where encounter_id=current_setting('test.eid')::uuid and status='queued'),true);
select is((select r->>'extractionStatus' from phi.demo_jobs j cross join lateral jsonb_array_elements(j.snapshot->'reports') r where j.id=current_setting('test.currentjob')::uuid and r->>'id'=current_setting('test.r2')),'failed','replacement snapshot records failure as unknown evidence');
set local role service_role;
select set_config('test.claim',api.demo_worker('claim',current_setting('test.currentjob')::uuid)::text,true);
select is(current_setting('test.claim')::jsonb->>'ok','true','assessment can run after all reports reach terminal states');
select is((select r->'fields'->0->>'reportType' from jsonb_array_elements(current_setting('test.claim')::jsonb->'data'->'reports') r where r->>'id'=current_setting('test.r1')),'ultrasound','claimed job carries type-aware report finding without staff verification');
reset role;
select set_config('request.jwt.claims','{"sub":"94000000-0000-4000-8000-000000000001","session_id":"94000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
select set_config('test.currentversion',(select version::text from phi.encounters where id=current_setting('test.eid')::uuid),true);
set local role authenticated;
select is(api.begin_staff_session()->>'ok','true','staff correction session starts');
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.r1'),'sourceVersion',current_setting('test.currentversion')::int,'fields',jsonb_build_array(current_setting('test.validfield')::jsonb||bad.patch)))->>'ok','false','direct staff RPC rejects malformed correction: '||bad.label)
 from (values ('page zero','{"page":0}'::jsonb),('missing label','{"label":null}'),('unsupported type','{"reportType":"invented"}'),('string verification','{"verified":"false"}')) bad(label,patch);
select is(api.demo_action('report_verify',current_setting('test.eid')::uuid,null,jsonb_build_object('reportId',current_setting('test.r1'),'sourceVersion',current_setting('test.currentversion')::int,'fields','[{"id":"p1-f1","label":"Printed observation","value":"Corrected fictional observation","unit":"","page":1,"sourceText":"Corrected fictional observation","date":"2026-09-01","reportType":"ultrasound","confidence":"text-extracted","verified":true}]'::jsonb))->>'ok','true','staff may optionally correct source evidence');
reset role;
select is((select fields->0->>'confidence' from phi.demo_reports where id=current_setting('test.r1')::uuid),'manual-transcription','staff edit cannot masquerade as untouched machine extraction');
select is((select clinician_draft->>'impression' from phi.encounters where id=current_setting('test.eid')::uuid),'Saved fictional draft','optional report corrections also preserve authored draft');
set local role service_role;
select is(api.demo_worker('complete',current_setting('test.currentjob')::uuid,(current_setting('test.claim')::jsonb->'data'->>'lease')::uuid,'{"urgency":"review"}')->>'ok','false','late assessment cannot publish after evidence correction');
reset role;
select ok(exists(select 1 from audit.audit_events where action='demo_report_worker_complete' and record_ids=array[current_setting('test.eid')::uuid] and outcome='allowed'),'automatic report publication is audited');
select throws_ok(format('update phi.demo_jobs set snapshot=''{}'' where id=%L',current_setting('test.currentjob')),'P0001','Job source is immutable','old snapshots remain immutable');
-- Simulate a clinician release during an already claimed report extraction.
update phi.demo_reports set extraction_status='queued',extraction_attempts=0 where id=current_setting('test.r2')::uuid;
set local role service_role;
select set_config('test.lease',api.report_worker('claim',current_setting('test.r2')::uuid)->'data'->>'lease',true);
reset role;
update phi.encounters set released_at=now() where id=current_setting('test.eid')::uuid;
select set_config('test.releasedversion',(select version::text from phi.encounters where id=current_setting('test.eid')::uuid),true);
set local role service_role;
select is(api.report_worker('complete',current_setting('test.r2')::uuid,current_setting('test.lease')::uuid,'{"fields":[],"quality":"Empty"}')->>'ok','false','report cannot change a released plan');
reset role;
select is((select version::text from phi.encounters where id=current_setting('test.eid')::uuid),current_setting('test.releasedversion'),'released source version remains unchanged');
-- Intake-stage extraction must not stale patient answer autosaves. Submission freezes it.
select set_config('request.jwt.claims','{}',true);
set local role service_role;
select set_config('test.entry2',api.patient_start('automatic-test')::text,true);
select set_config('test.eid2',current_setting('test.entry2')::jsonb->'data'->>'id',true);
select set_config('test.cap2',current_setting('test.entry2')::jsonb->'data'->>'token',true);
reset role;set local role anon;
select api.demo_action('consent',current_setting('test.eid2')::uuid,current_setting('test.cap2'),'{"accepted":true,"noticeVersion":"gi-privacy-2026-09-22"}');
select api.demo_action('save',current_setting('test.eid2')::uuid,current_setting('test.cap2'),'{"version":0,"intake":{"name":"Fictional intake-stage patient","age":40,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":5,"answers":{}}}');
select api.demo_action('report_add',current_setting('test.eid2')::uuid,current_setting('test.cap2'),'{"name":"fictional-mri.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[],"quality":"pending"}');
reset role;
select set_config('test.r3',(select id::text from phi.demo_reports where encounter_id=current_setting('test.eid2')::uuid),true);
select set_config('test.intakeversion',(select version::text from phi.encounters where id=current_setting('test.eid2')::uuid),true);
set local role service_role;
select set_config('test.lease',api.report_worker('claim',current_setting('test.r3')::uuid)->'data'->>'lease',true);
select is(api.report_worker('complete',current_setting('test.r3')::uuid,current_setting('test.lease')::uuid,jsonb_build_object('fields',jsonb_build_array(current_setting('test.validfield')::jsonb||'{"reportType":"mri"}'::jsonb),'quality','Available'))->>'ok','true','extraction completes while questionnaire is still in progress');
reset role;
select is((select version::text from phi.encounters where id=current_setting('test.eid2')::uuid),current_setting('test.intakeversion'),'background extraction does not conflict with patient autosave');
set local role anon;
select is(api.demo_action('submit',current_setting('test.eid2')::uuid,current_setting('test.cap2'))->>'ok','true','intake-stage findings submit without staff intervention');
reset role;
select is((select snapshot->'reports'->0->'fields'->0->>'reportType' from phi.demo_jobs where encounter_id=current_setting('test.eid2')::uuid),'mri','submission snapshot already contains completed machine findings');
-- An explicit clinician partial-intake review has no AI job. Completion must not create one.
set local role service_role;
select set_config('test.entry3',api.patient_start('automatic-test')::text,true);
select set_config('test.eid3',current_setting('test.entry3')::jsonb->'data'->>'id',true);
select set_config('test.cap3',current_setting('test.entry3')::jsonb->'data'->>'token',true);
reset role;set local role anon;
select api.demo_action('consent',current_setting('test.eid3')::uuid,current_setting('test.cap3'),'{"accepted":true,"noticeVersion":"gi-privacy-2026-09-22"}');
select api.demo_action('save',current_setting('test.eid3')::uuid,current_setting('test.cap3'),'{"version":0,"intake":{"name":"Fictional partial patient","age":40,"sex":"Male","suppliedBy":"patient","enteredBy":"patient","relationship":"","stage":5,"answers":{}}}');
select api.demo_action('report_add',current_setting('test.eid3')::uuid,current_setting('test.cap3'),'{"name":"fictional-blood.pdf","mime":"application/pdf","body":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","fields":[],"quality":"pending"}');
reset role;
select set_config('test.r4',(select id::text from phi.demo_reports where encounter_id=current_setting('test.eid3')::uuid),true);
select set_config('request.jwt.claims','{"sub":"94000000-0000-4000-8000-000000000001","session_id":"94000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
set local role authenticated;
select is(api.demo_action('review_partial',current_setting('test.eid3')::uuid)->>'ok','true','clinician explicitly takes partial intake for human review');
reset role;
update phi.encounters set clinician_draft='{"impression":"Partial-review draft"}',draft_source_version=version where id=current_setting('test.eid3')::uuid;
set local role service_role;
select set_config('test.lease',api.report_worker('claim',current_setting('test.r4')::uuid)->'data'->>'lease',true);
select is(api.report_worker('complete',current_setting('test.r4')::uuid,current_setting('test.lease')::uuid,jsonb_build_object('fields',jsonb_build_array(current_setting('test.validfield')::jsonb||'{"reportType":"blood-test"}'::jsonb),'quality','Available'))->>'ok','true','report still processes during partial review');
reset role;
select is((select count(*)::int from phi.demo_jobs where encounter_id=current_setting('test.eid3')::uuid),0,'report completion does not introduce AI for an unsubmitted partial intake');
select is((select clinician_draft->>'impression' from phi.encounters where id=current_setting('test.eid3')::uuid),'Partial-review draft','partial-review draft survives new evidence');
select ok((select draft_source_version<version from phi.encounters where id=current_setting('test.eid3')::uuid),'partial-review draft is explicitly linked to older evidence');
select * from finish();
