import { existsSync, readFileSync } from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { connectCloud, verifyLedger } from "./cloud.mjs";
import { scenarios } from "../src/lib/demo/fixtures";
import prompts from "../src/lib/ai/prompts.json";
for (const file of [".env", ".env.operator", ".env.test"])
  if (existsSync(file)) process.loadEnvFile(file);
const kind = process.argv.includes("--test") ? "test" : "demo";
const fresh = process.argv.includes("--current-prompt");
const clinicOnly = process.argv.includes("--clinic-only");
const operator = process.env.OPERATOR_ID;
if (!operator) throw new Error("OPERATOR_ID_REQUIRED");
const { client: db } = await connectCloud(kind);
let created = 0;
try {
  await verifyLedger(db);
  await db.query("begin");
  const readId = randomUUID();
  await db.query(
    "insert into audit.operator_events(operator_id,reason_code,action,request_id,outcome,resource_type) values($1,'synthetic_rehearsal','demo_seed_read',$2,'intent','encounter')",
    [operator, readId],
  );
  const patients = await db.query(
    "select p.id,p.site_id,p.synthetic_identifier,(select m.user_id from app.site_memberships m join app.staff_accounts a on a.user_id=m.user_id where m.site_id=p.site_id and m.role='clinician' and m.active and a.active order by m.user_id limit 1) as reviewer from phi.patients p where p.site_id in('11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222') and p.is_synthetic and p.synthetic_identifier ~ '^SYN-(CLINIC|HOSPITAL)-00[1-3]$' and (not $1::boolean or p.site_id='11111111-1111-4111-8111-111111111111') order by p.site_id,p.synthetic_identifier",
    [clinicOnly],
  );
  for (const [index, patient] of patients.rows.entries()) {
    if (!patient.reviewer) throw new Error("REVIEWER_REQUIRED");
    const scenario = scenarios[index % scenarios.length];
    const intake = { ...scenario.intake, stage: 6 };
    const h = createHash("sha256")
      .update(`hospital-demo-${fresh ? prompts.version : "v1"}:${patient.id}`)
      .digest("hex");
    const id = `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
    if (
      (await db.query("select id from phi.encounters where id=$1", [id]))
        .rowCount
    )
      continue;
    const requestId = randomUUID();
    await db.query(
      "insert into audit.operator_events(operator_id,reason_code,action,request_id,outcome,site_id,record_ids,resource_type) values($4,'synthetic_rehearsal','demo_seed',$1,'intent',$2,$3,'encounter')",
      [requestId, patient.site_id, [id], operator],
    );
    await db.query(
      "insert into phi.encounters(id,site_id,patient_id,assigned_to,consent_at,notice_version,status,version,intake) values($1,$2,$3,$4,now(),'synthetic-fixture-v1','queued',1,$5)",
      [id, patient.site_id, patient.id, patient.reviewer, intake],
    );
    await db.query(
      "insert into phi.encounter_versions(encounter_id,site_id,version,intake) values($1,$2,1,$3)",
      [id, patient.site_id, intake],
    );
    if (fresh && scenario.id === "bowel") {
      for (const name of [
        "synthetic-whole-body-report.pdf",
        "synthetic-written-imaging-report.pdf",
      ]) {
        await db.query(
          "insert into phi.demo_reports(encounter_id,site_id,name,mime,body,fields,quality) values($1,$2,$3,'application/pdf',$4,'[]','Waiting for automatic extraction')",
          [
            id,
            patient.site_id,
            name,
            readFileSync(`public/demo-assets/${name}`).toString("base64"),
          ],
        );
      }
    }
    await db.query(
      "insert into phi.demo_jobs(encounter_id,site_id,source_version) values($1,$2,1)",
      [id, patient.site_id],
    );
    await db.query(
      "insert into audit.operator_events(operator_id,reason_code,action,request_id,outcome,site_id,record_ids,resource_type) values($4,'synthetic_rehearsal','demo_seed',$1,'completed',$2,$3,'encounter')",
      [requestId, patient.site_id, [id], operator],
    );
    created++;
    console.log(`Prepared ${scenario.id}: ${id.slice(0, 8).toUpperCase()}`);
  }
  await db.query(
    "insert into audit.operator_events(operator_id,reason_code,action,request_id,outcome,resource_type) values($1,'synthetic_rehearsal','demo_seed_read',$2,'completed','encounter')",
    [operator, readId],
  );
  await db.query("commit");
  console.log(
    `${created} prepared fictional encounters added to ${kind}. Existing encounters were preserved. AI outputs will be generated by the configured worker.`,
  );
} catch (e) {
  await db.query("rollback");
  console.log(
    `Fixture setup failed: ${e instanceof Error && /^[A-Z_]+$/.test(e.message) ? e.message : "database_error"}`,
  );
  process.exitCode = 1;
} finally {
  await db.end();
}
