import type { Intake } from "./clinical";
// Entirely fictional authored examples. Never default unasked patient answers to negative.
export const blankIntake: Intake = {
  name: "",
  age: 0,
  sex: "Prefer not to answer",
  suppliedBy: "patient",
  enteredBy: "patient",
  relationship: "",
  stage: 1,
  answers: {},
};
export const scenarios: Array<{
  id: string;
  title: string;
  description: string;
  intake: Intake;
}> = [
  {
    id: "bowel",
    title: "Aarav Mehra · 52 · fictional",
    description:
      "Six weeks of altered bowel habits, intermittent blood and weight loss. Optional whole-body report.",
    intake: {
      name: "Aarav Mehra (fictional)",
      age: 52,
      sex: "Male",
      suppliedBy: "patient",
      enteredBy: "patient",
      relationship: "",
      stage: 1,
      answers: {
        pain_site: '["Lower middle"]',
        faint: "Neither lightheadedness nor fainting",
        vomit_blood: "No blood noticed / no vomiting",
        black_stool: "No black stool",
        rectal_blood: "Blood mixed into the stool or toilet water",
        vomiting: "No vomiting",
        fluids: "Usual drinks stay down",
        distended: "No unusual swelling",
        no_gas: "Passing both stool and gas",
        jaundice: "No yellowing noticed",
        fever: "No fever noticed",
        swallowing: "No difficulty swallowing",
        concern: "Bowel habits changed with occasional blood mixed in stool.",
        duration: "3–6 weeks ago",
        pattern: "Getting worse",
        pain_score: "3",
        pain_character: "Cramping or waves",
        pain_radiates: '["Stays in the same place"]',
        food_effect: "No clear effect",
        reflux: "None of these",
        early_full: "Can finish a usual meal",
        appetite: "Less appetite than usual",
        weight_loss: "Lost weight without trying",
        weight_details:
          "About 4 kg over 2 months, estimated from clothes and home scale.",
        itching: "No itching",
        bowel_change: "Alternating hard and loose stools",
        stool_colour: "Red or blood mixed in",
        mucus: "Occasionally",
        bleeding_details:
          "Small streaks mixed in the stool two or three times a week.",
        fatigue: "More tired but can do usual activities",
        medicines:
          "OTC antacid occasionally for 3 weeks. No blood thinner or regular painkiller reported.",
        allergies: "No known medicine allergy, patient confirmed.",
        conditions: "No diagnosed chronic illness reported.",
        surgery: "Appendix removed in 2004. No previous colonoscopy.",
        family: "Father had colorectal cancer at age 68.",
        first_symptom_date: "Approximately 10 August 2026.",
        first_contact: "Pharmacist",
        previous_treatment:
          "First pharmacy visit in August; treated as constipation. Laxative helped briefly.",
        previous_tests:
          "Whole-body blood tests on 18 September 2026. No colonoscopy yet.",
        confusion: "No change in awareness",
        urine: "About the usual amount",
        pain_presence: "Pain comes and goes; no pain right now",
        pain_onset: "Gradually, over hours or days",
        pain_started: "3–6 weeks ago",
        pain_pattern: "Comes and goes, with pain-free periods",
        pain_frequency: "Most days",
        pain_episode_length: "Less than an hour",
        pain_relief: "Settles on its own",
        medicines_status: "Both prescription and other remedies",
        allergy_status: "No known allergies",
        family_status: "Cancer in a blood relative",
        tobacco: "Never used",
        tb_history: "Not sure",
        visits: "2–3",
        previous_tests_status: "Tests done, reports available",
        first_contact_date:
          "Approximately August or September 2026, see prior treatment details.",
        referral:
          "One pharmacy visit and one general physician consultation. GP advised specialist review.",
        rectal_blood_timing: "Within the past week, now stopped",
        rectal_blood_amount: "A few spots or streaks",
        appearance_stool_timing: "Within the past week, now stopped",
        appearance_stool_amount: "A few spots or streaks",
        bowel_frequency:
          "Usually once daily; now hard stool for 2 days then 3 loose stools. About 6 weeks.",
      },
    },
  },
  {
    id: "no-report",
    title: "Kavita Rao · 47 · fictional",
    description:
      "Persistent upper abdominal fullness and early satiety after weeks of acidity treatment. No reports.",
    intake: {
      name: "Kavita Rao (fictional)",
      age: 47,
      sex: "Female",
      suppliedBy: "caregiver",
      enteredBy: "patient",
      relationship: "Daughter",
      stage: 1,
      answers: {
        pain_site: '["Upper middle"]',
        faint: "Neither lightheadedness nor fainting",
        vomit_blood: "No blood noticed / no vomiting",
        black_stool: "No black stool",
        rectal_blood: "No red blood noticed",
        vomiting: "No vomiting",
        fluids: "Usual drinks stay down",
        distended: "No unusual swelling",
        no_gas: "Passing both stool and gas",
        jaundice: "No yellowing noticed",
        fever: "No fever noticed",
        swallowing: "No difficulty swallowing",
        concern: "Upper abdominal fullness and eating less for about 2 months.",
        duration: "2–3 months ago",
        pattern: "Getting worse",
        pain_score: "4",
        pain_radiates: '["Back"]',
        food_effect: "Usually makes it worse",
        reflux: "Burning in the upper tummy",
        early_full: "Usually full after a small amount",
        appetite: "Less appetite than usual",
        weight_loss: "Lost weight without trying",
        weight_details: "3 kg over 2 months, estimated.",
        itching: "No itching",
        bowel_change: "No change",
        stool_colour: "Brown",
        mucus: "Not noticed",
        fatigue: "More tired but can do usual activities",
        medicines:
          "Acidity tablets from pharmacy for 6 weeks; exact name not known. Herbal remedy occasionally.",
        allergies: "Not known.",
        conditions: "Type 2 diabetes diagnosed 3 years ago.",
        surgery: "No surgery reported. No endoscopy.",
        family: "Not known.",
        first_symptom_date: "Late July 2026, approximate.",
        first_contact: "Pharmacist",
        previous_treatment:
          "Treated as gas/acidity for 6 weeks. Initially some relief, symptoms returned.",
        previous_tests: "No reports or prior investigations available.",
        confusion: "No change in awareness",
        urine: "About the usual amount",
        pain_presence: "Pain comes and goes; no pain right now",
        pain_onset: "Gradually, over hours or days",
        pain_started: "2–3 months ago",
        pain_pattern: "Comes and goes, with pain-free periods",
        pain_frequency: "Most days",
        pain_episode_length: "Less than an hour",
        pain_relief: "Settles on its own",
        medicines_status: "Both prescription and other remedies",
        allergy_status: "Not sure",
        family_status: "Not sure",
        tobacco: "Never used",
        tb_history: "Not sure",
        visits: "2–3",
        previous_tests_status: "No tests yet",
        first_contact_date:
          "Approximately August or September 2026, see prior treatment details.",
        referral: "Two pharmacy visits; no specialist visit yet.",
      },
    },
  },
  {
    id: "jaundice",
    title: "Rohan Sethi · 61 · fictional",
    description:
      "Yellow eyes, dark urine and itching; demonstrates the imaging report pathway.",
    intake: {
      name: "Rohan Sethi (fictional)",
      age: 61,
      sex: "Male",
      suppliedBy: "patient",
      enteredBy: "patient",
      relationship: "",
      stage: 1,
      answers: {
        pain_site: '["Right upper"]',
        faint: "Neither lightheadedness nor fainting",
        vomit_blood: "No blood noticed / no vomiting",
        black_stool: "No black stool",
        rectal_blood: "No red blood noticed",
        vomiting: "No vomiting",
        fluids: "Usual drinks stay down",
        distended: "No unusual swelling",
        no_gas: "Passing both stool and gas",
        jaundice: "Yellow now / recently noticed",
        fever: "No fever noticed",
        swallowing: "No difficulty swallowing",
        concern: "Yellow eyes, dark urine and itching for 10 days.",
        duration: "1–2 weeks ago",
        pattern: "Getting worse",
        pain_score: "3",
        pain_radiates: '["Back"]',
        food_effect: "No clear effect",
        reflux: "None of these",
        early_full: "Usually full after a small amount",
        appetite: "Less appetite than usual",
        weight_loss: "Lost weight without trying",
        weight_details: "5 kg over 3 months, measured on home scale.",
        itching: "All over",
        bowel_change: "No change",
        stool_colour: "Pale or clay coloured",
        mucus: "Not noticed",
        fatigue: "More tired but can do usual activities",
        medicines:
          "Metformin for diabetes. No recent antibiotics or herbal medicines reported.",
        allergies: "Not known.",
        conditions: "Diabetes for 8 years; gallstones found previously.",
        surgery: "No abdominal surgery reported.",
        family: "No known family GI cancer, patient confirmed.",
        first_symptom_date: "Approximately 11 September 2026.",
        first_contact: "General physician",
        previous_treatment:
          "GP seen after 3 days of yellow eyes; requested blood tests and abdominal imaging.",
        previous_tests:
          "Abdominal imaging requested. Bring existing reports if available.",
        confusion: "No change in awareness",
        urine: "About the usual amount",
        pain_presence: "Pain comes and goes; no pain right now",
        pain_onset: "Gradually, over hours or days",
        pain_started: "1–2 weeks ago",
        pain_pattern: "Comes and goes, with pain-free periods",
        pain_frequency: "Most days",
        pain_episode_length: "Less than an hour",
        pain_relief: "Settles on its own",
        medicines_status: "Both prescription and other remedies",
        allergy_status: "Not sure",
        family_status: "Not sure",
        tobacco: "Used previously, now stopped",
        tb_history: "Not sure",
        visits: "1",
        previous_tests_status: "Tests done, reports available",
        first_contact_date:
          "Approximately August or September 2026, see prior treatment details.",
        referral: "One GP consultation; referred for specialist review.",
        jaundice_started: "1–2 weeks ago",
        jaundice_pattern: "Getting more noticeable",
        urine_colour: "Tea or cola coloured",
        itch_impact: "Disturbs sleep",
        tobacco_details:
          "Stopped smoking 10 years ago. No current alcohol reported.",
      },
    },
  },
];
